src/book/bean/BookInfoBean.java
/**
/**
 *
 */
package book.bean;

import java.io.Serializable;
import java.sql.Date;

import book.dao.CategoryDAO;
import book.dao.PublisherDAO;
import exception.DAOException;

public class BookInfoBean implements Serializable {
	/** 本のiSBN番号 */
	private String isbn = "";

	/** 本の分類番号 */
	private int categoryCode = -1;

	/** 出版社コード */
	private int publisherCode = -1;

	/** 本の名前 */
	private String bookName = "";

	/** 著者 */
	private String author = "";

	/** 出版日 */
	private Date publicationDay = null;

	public BookInfoBean() {

	}

	public BookInfoBean(String isbn, int categoryCode, int publisherCode, String bookName, String author, Date publicationDay) {
		setIsbn(isbn);
		setCategoryCode(categoryCode);
		setPublisherCode(publisherCode);
		setBookName(bookName);
		setAuthor(author);
		setPublicationDay(publicationDay);
	}

	public String getIsbn() {
		return isbn;
	}
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}
	public int getCategoryCode() {
		return categoryCode;
	}
	public void setCategoryCode(int categoryCode) {
		this.categoryCode = categoryCode;
	}
	public int getPublisherCode() {
		return publisherCode;
	}
	public void setPublisherCode(int publisherCode) {
		this.publisherCode = publisherCode;
	}
	public String getBookName() {
		return bookName;
	}
	public void setBookName(String bookName) {
		this.bookName = bookName;
	}
	public String getAuthor() {
		return author;
	}
	public void setAuthor(String author) {
		this.author = author;
	}
	public Date getPublicationDay() {
		return publicationDay;
	}
	public void setPublicationDay(Date publicationDay) {
		this.publicationDay = publicationDay;
	}

	public String getCategoryName() {
		String name = "";
		try {
			CategoryDAO dao = new CategoryDAO();
			name = dao.selectByCategoryCode(this.categoryCode);
		} catch (DAOException e) {
			e.printStackTrace();
		}
		return name;
	}

	public String getPublisherName() {
		String name="";
		try {
			PublisherDAO dao = new PublisherDAO();
			name = dao.selectByPublisherCode(this.publisherCode);
		} catch (DAOException e) {
			e.printStackTrace();
		}
		return name;
	}

}

src/book/servlet/BookAddCompleteServlet.java
/**
 * 図書追加完了のServlet
 * @author chibatoshinori
 */

package book.servlet;

import java.io.IOException;
import java.sql.Date;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import book.bean.BookInfoBean;
import book.bean.BookStateBean;
import book.dao.BookStateDAO;
import exception.DAOException;

/**
 * Servlet implementation class BookAddCompleteServlet
 */
@WebServlet("/BookAddCompleteServlet")
public class BookAddCompleteServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public BookAddCompleteServlet() {
		super();
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// リクエストの文字コードを指定
		request.setCharacterEncoding("UTF-8");

		// 入荷個数を取得
		int num = Integer.parseInt(request.getParameter("num"));
		HttpSession session = request.getSession();
		BookInfoBean bean = (BookInfoBean) session.getAttribute("bean");

		Date today = new Date(System.currentTimeMillis());

		BookStateBean book = new BookStateBean(bean.getIsbn(), bean.getBookName(), today);
		BookStateDAO dao;
		try {
			dao = new BookStateDAO();
			for (int i=0; i < num; i++) {
				dao.insertBookState(book);
			}
			gotoPage(request, response, "/WEB-INF/bookAddCompleteView.jsp");
		} catch (DAOException e) {
			gotoPage(request, response, "/WEB-INF/error.jsp");
			e.printStackTrace();
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}
	private void gotoPage(HttpServletRequest request, HttpServletResponse response, String page) throws ServletException, IOException {
		RequestDispatcher rd = request.getRequestDispatcher(page);
		rd.forward(request, response);
	}
}

src/book/servlet/BookCatalogAddCompleteServlet.java
/**
 * 目録追加を完了するServlet
 * @author chibatoshinori
 */

package book.servlet;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import book.bean.BookInfoBean;
import book.dao.BookInfoDAO;
import exception.DAOException;

/**
 * Servlet implementation class BookCatalogAddCompleteServlet
 */
@WebServlet("/BookCatalogAddCompleteServlet")
public class BookCatalogAddCompleteServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
    /**
     * @see HttpServlet#HttpServlet()
     */
    public BookCatalogAddCompleteServlet() {
        super();
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		request.setCharacterEncoding("UTF-8");

		HttpSession session = request.getSession();
		BookInfoBean bean = (BookInfoBean) session.getAttribute("bean");
		try {
			BookInfoDAO dao = new BookInfoDAO();
			// 既に同じISBNが存在していないかのチェック
			BookInfoBean confirm = dao.selectByISBN(bean.getIsbn());
			if (confirm !=null) {
				String error = "既に目録に追加されています。";
				request.setAttribute("error", error);
				gotoPage(request, response, "/WEB-INF/rentalerror.jsp");
				return;
			}
			dao.insertBookInfo(bean);
			gotoPage(request, response, "/WEB-INF/bookCatalogAddCompleteView.jsp");
		} catch (DAOException e) {
			gotoPage(request, response, "/WEB-INF/error.jsp");
			e.printStackTrace();
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}
	private void gotoPage(HttpServletRequest request, HttpServletResponse response, String page) throws ServletException, IOException {
		RequestDispatcher rd = request.getRequestDispatcher(page);
		rd.forward(request, response);
	}

}

src/book/servlet/BookDeleteCompleteServlet.java
/**
 * 図書の廃棄を完了するServlet
 * @author chibatoshinori
 */

package book.servlet;

import java.io.IOException;
import java.sql.Date;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import book.bean.BookStateBean;
import book.dao.BookStateDAO;
import exception.DAOException;

/**
 * Servlet implementation class BookDeleteCompleteServlet
 */
@WebServlet("/BookDeleteCompleteServlet")
public class BookDeleteCompleteServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public BookDeleteCompleteServlet() {
		super();
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// リクエストパラメータの文字コードを指定
		request.setCharacterEncoding("UTF-8");

		HttpSession session = request.getSession();
		BookStateBean bean = (BookStateBean) session.getAttribute("book");
		try {
			if (bean != null) {
				BookStateDAO dao = new BookStateDAO();
				BookStateBean confirm = dao.selectByBookId(bean.getBookId());
				if (confirm != null && confirm.getDisposalDate() != null) {
					String error = "既に廃棄されています。";
					request.setAttribute("error", error);
					gotoPage(request, response, "/WEB-INF/rentalerror.jsp");
					return;
				}
				Date today = new Date(System.currentTimeMillis());
				int id = bean.getBookId();
				BookStateBean book = new BookStateBean();
				book.setDisposalDate(today);
				dao.updateBookState(book, id);
				request.setAttribute("action", "disposal");
				gotoPage(request, response, "/WEB-INF/bookDeleteCompleteView.jsp");
			}
		} catch (DAOException e) {
			gotoPage(request, response, "/WEB-INF/error.jsp");
			e.printStackTrace();
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

	private void gotoPage(HttpServletRequest request, HttpServletResponse response, String page) throws ServletException, IOException {
		RequestDispatcher rd = request.getRequestDispatcher(page);
		rd.forward(request, response);
	}

}

src/book/servlet/BookEditCompleteServlet.java
/**
 * 図書情報の編集を完了するServlet
 * @author chibatoshinori
 */

package book.servlet;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import book.bean.BookInfoBean;
import book.dao.BookInfoDAO;
import exception.DAOException;

/**
 * Servlet implementation class BookEditCompleteServlet
 */
@WebServlet("/BookEditCompleteServlet")
public class BookEditCompleteServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * @see HttpServlet#HttpServlet()
     */
    public BookEditCompleteServlet() {
        super();
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		request.setCharacterEncoding("UTF-8");

		HttpSession session = request.getSession();
		// セッション領域からbeanを取得
		BookInfoBean book = (BookInfoBean) session.getAttribute("book");
		BookInfoBean bean = (BookInfoBean) session.getAttribute("bean");

		// セッション領域に格納されている値の破棄
		session.removeAttribute("book");
		session.removeAttribute("bean");

		// daoでデータベースの更新
		try {
			BookInfoDAO dao = new BookInfoDAO();
			// BookStateDAO sdao = new BookStateDAO();

			/* book_stateのデータを更新
			List<BookStateBean> list = sdao.selectByISBN(book.getIsbn());
			BookStateBean sbean = new BookStateBean();
			sbean.setIsbn(bean.getIsbn());
			sbean.setBookName(bean.getBookName());
			for (BookStateBean b : list) {
				sdao.updateBookState(sbean, b.getBookId());
			}*/
			int rows = dao.updateBookInfo(bean, book.getIsbn());
			request.setAttribute("rows", rows);

			gotoPage(request, response, "/WEB-INF/bookEditCompleteView.jsp");
		} catch (DAOException e) {
			gotoPage(request, response, "/WEB-INF/error.jsp");
			e.printStackTrace();
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

	private void gotoPage(HttpServletRequest request, HttpServletResponse response, String page) throws ServletException, IOException {
		RequestDispatcher rd = request.getRequestDispatcher(page);
		rd.forward(request, response);
	}
}

src/book/servlet/BookEditConfirmServlet.java
/**
 * 入力された情報を取得してBeanに格納し、確認画面に遷移するServlet
 * @author chibatoshinori
 */

package book.servlet;

import java.io.IOException;
import java.sql.Date;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import book.bean.BookInfoBean;
import book.dao.BookInfoDAO;

/**
 * Servlet implementation class BookEditConfirmServlet
 */
@WebServlet("/BookEditConfirmServlet")
public class BookEditConfirmServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * @see HttpServlet#HttpServlet()
     */
    public BookEditConfirmServlet() {
        super();
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		request.setCharacterEncoding("UTF-8");

		// 各パラメータの取得
		String isbn = request.getParameter("isbn");
		int categoryCode = Integer.parseInt(request.getParameter("category"));
		String bookName = request.getParameter("bookName");
		String author = request.getParameter("author");
		int publisherCode = Integer.parseInt(request.getParameter("publisher"));
		String publication = request.getParameter("publication");
		Date publicationDay = null;

		if (!publication.equals("")) {
			publicationDay = Date.valueOf(publication);
			Date today = new Date(System.currentTimeMillis());
			if (publicationDay.after(today)) {
				String error = "出版日の値が不正です。本日より前の日付けを入力してください。";
				request.setAttribute("error", error);
				gotoPage(request, response, "/WEB-INF/rentalerror.jsp");
				return;
			}
		}

		try {
			BookInfoDAO dao = new BookInfoDAO();
			BookInfoBean bean = dao.selectByISBN(isbn);
			if (bean != null) {
				// すでにそのISBNの本が存在するのでエラー画面に遷移
				String error = "既に指定されたISBN番号の目録情報が存在するため変更することができません";
				request.setAttribute("error", error);
				gotoPage(request, response, "/WEB-INF/rentalerror.jsp");
				return;
			}
		} catch (Exception e){
			gotoPage(request, response, "/WEB-INF/error.jsp");
			e.printStackTrace();
			return;
		}
		// BookInfoBeanに格納
		BookInfoBean bean = new BookInfoBean(isbn, categoryCode, publisherCode, bookName, author, publicationDay);
		// セッション領域に格納
		HttpSession session = request.getSession();
		session.setAttribute("bean", bean);
		// 確認画面へ遷移
		gotoPage(request, response, "/WEB-INF/bookEditConfirmView.jsp");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

	private void gotoPage(HttpServletRequest request, HttpServletResponse response, String page) throws ServletException, IOException {
		RequestDispatcher rd = request.getRequestDispatcher(page);
		rd.forward(request, response);
	}

}

src/book/servlet/BookEditServlet.java
/**
 * ISBNb番号を取得して存在するかどうかを調べた後にあった場合は検索結果画面に遷移させるServlet
 * @author chibatoshinori
 */
package book.servlet;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import book.bean.BookInfoBean;
import book.dao.BookInfoDAO;

/**
 * Servlet implementation class BookEditServlet
 */
@WebServlet("/BookEditServlet")
public class BookEditServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public BookEditServlet() {
		super();
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// リクエストの文字コードを指定
		request.setCharacterEncoding("UTF-8");
		// リクエストから検索に使うbookIdを取得
		String isbn = request.getParameter("isbn");
		//

		try {
			BookInfoDAO dao = new BookInfoDAO();
			BookInfoBean bean = dao.selectByISBN(isbn);
			if (bean == null) {
				String error = "入力されたISBN番号に対応する図書目録が存在しません。";
				request.setAttribute("error", error);
				gotoPage(request, response, "/WEB-INF/rentalerror.jsp");
				return;
			} else {
				// セッションスコープに入れる
				HttpSession session = request.getSession();
				session.setAttribute("book", bean);
				// ディスパッチ
				gotoPage(request, response, "/WEB-INF/bookEditSelectView.jsp");
				return;
			}
		} catch (Exception e) {
			gotoPage(request, response, "/WEB-INF/error.jsp");
			e.printStackTrace();
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

	private void gotoPage(HttpServletRequest request, HttpServletResponse response, String page) throws ServletException, IOException {
		RequestDispatcher rd = request.getRequestDispatcher(page);
		rd.forward(request, response);
	}
}

WebContent/WEB-INF/RecieveFinish.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<% String message="正常に返却処理が完了しました"; %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>返却完了</title>
    <link href="/library/style.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/library/js/template.js"></script>
</head>
<body>
<!--ヘッダー-->
<header>
        <h1>図書管理システム</h1>
    </header>

    <div class="container">
        <div class="main">

		<%=message %>

        </div>
        <div class="sidebar">
            <script type="text/javascript">
            	sidebar();
            </script>
        </div>
    </div>
    <!--/.container-->

    <footer id="footer">
    	<script type="text/javascript" >
			footer();
   		</script>
    </footer>
</body>
</html>

WebContent/WEB-INF/UserDeleteConfirmView.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ page import="user.bean.UserBean"%>


<!DOCTYPE html">
<html>
<head>
<meta http-equiv="UTF-8">
<title>退会表示</title>

<link href="/library/style.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="./js/template.js"></script>

</head>
<body>
<!--ヘッダー-->
	<header>
		<h1>図書管理システム</h1>
	</header>
	<div class="container">
		<div class="main">
		<h3>退会完了</h3>
			会員の退会処理が完了しました。
		</div>
		<div class="sidebar">
			<script type="text/javascript">
            	sidebar();
            </script>
		</div>
	</div>
	<!--/.container-->

	<footer id="footer">
		<script type="text/javascript">
			footer();
   		</script>
	</footer>
</body>
</html>

WebContent/WEB-INF/UserEditConfirmView.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>


<!DOCTYPE html">
<html>
<head>
<meta http-equiv="UTF-8">
<title>会員情報編集確認画面</title>
<link href="/library/style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="./js/template.js"></script>
</head>
</body>
<!--ヘッダー-->
	<header>
		<h1>図書管理システム</h1>
	</header>

	<div class="container">

		<div class="main">
		<h2>会員情報の編集</h2>
			以下のように書き換えます。よろしいですか?
			<form action="/library/UserEditCompleteServlet" method="get">
				<table border>
					<tbody>
						<tr>
							<td></td>
							<td>変更前</td>
							<td>変更後</td>
						</tr>
						<tr>
							<td>利用者苗字</td>
							<td>${bean.familyName }</td>
							<td>${user.familyName }</td>
						</tr>
						<tr>
							<td>利用者名前</td>
							<td>${bean.name}</td>
							<td>${user.name}</td>
						</tr>
						<tr>
							<td>利用者生年月日</td>
							<td>${bean.birthday}</td>
							<td>${user.birthday}</td>
						</tr>
						<tr>
							<td>利用者電話番号</td>
							<td>${bean.tel}</td>
							<td>${user.tel}</td>
						</tr>
						<tr>
							<td>利用者メールアドレス</td>
							<td>${bean.email}</td>
							<td>${user.email }</td>
						</tr>
						<tr>
							<td>利用者郵便番号</td>
							<td>${bean.postal  }</td>
							<td>${user.postal  }</td>
						</tr>
						<tr>
							<td>利用者住所</td>
							<td>${bean.address }</td>
							<td>${user.address  }</td>
						</tr>

					</tbody>
				</table>
				<input type="submit" value="変更">
				<input type="button" value="戻る" onClick="history.back()">
			</form>
		</div>
		<div class="sidebar">
			<script type="text/javascript">
				sidebar();
			</script>
		</div>
	</div>
	<!--/.container-->

	<footer id="footer">
		<script type="text/javascript">
			footer();
		</script>
	</footer>








</body>
</html>

WebContent/WEB-INF/bookAddCompleteView.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>図書入荷完了画面</title>
<link href="/library/style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="./js/template.js"></script>
</head>
<body>
	<!--ヘッダー-->
	<header>
		<h1>図書管理システム</h1>
	</header>

	<div class="container">
		<div class="main">
			<h3>図書の入荷が完了しました</h3>
		</div>
		<div class="sidebar">
			<script type="text/javascript">
				sidebar();
			</script>
		</div>
	</div>
	<!--/.container-->

	<footer id="footer">
		<script type="text/javascript">
			footer();
		</script>
	</footer>
</body>
</html>

WebContent/WEB-INF/bookEditView.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="java.util.ArrayList"%>
<%@ page import="java.util.List"%>
<%@ page import="book.bean.CategoryBean"%>
<%@ page import="book.dao.CategoryDAO"%>
<%@ page import="book.bean.PublisherBean"%>
<%@ page import="book.dao.PublisherDAO"%>

<%
	CategoryDAO catedao = new CategoryDAO();
	List<CategoryBean> catelist = catedao.selectCategoryAll();
	request.setAttribute("catelist", catelist);

	PublisherDAO pubdao = new PublisherDAO();
	List<PublisherBean> publist = pubdao.selectPublisherAll();
	request.setAttribute("publist", publist);
%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>図書情報編集</title>
<link href="/library/style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="./js/template.js"></script>
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script
	src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
<script
	src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<link rel="stylesheet"
	href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/redmond/jquery-ui.css">

<script>
	$(function() {
		$("#datepicker").datepicker({
			maxDate : '0y', // 今日まで
			changeYear : true, // 表示年の指定が可能
			changeMonth : true, // 表示月の指定が可能
			dateFormat : 'yy-mm-dd' // 年-月-日
		});
	});
</script>
</head>
<body>
	<!--ヘッダー-->
	<header>
		<h1>図書管理システム</h1>
	</header>

	<div class="container">

		<div class="main">
			<h2>図書情報の編集</h2>
			図書情報を編集ができます。
			<form action="/library/BookEditConfirmServlet" method="get">
				<table border="1">
					<tbody>
						<tr>
							<td></td>
							<td>変更前</td>
							<td>変更後</td>
						</tr>
						<tr>
							<td>ISBN</td>
							<td>${book.isbn }</td>
							<td><input type="text" name="isbn" pattern="^[0-9]+$"
								maxlength="13"></td>
						</tr>
						<tr>
							<td>分類</td>
							<td>${book.categoryName }</td>
							<td><select name="category">
									<c:forEach items="${catelist }" var="cate">
										<option value="${cate.categoryCode }">${cate.categoryCode }.
											${cate.categoryName }</option>
									</c:forEach>
							</select></td>
						</tr>
						<tr>
							<td>書名</td>
							<td>${book.bookName }</td>
							<td><input type="text" name="bookName" maxlength="100"></td>
						</tr>
						<tr>
							<td>著者</td>
							<td>${book.author }</td>
							<td><input type="text" name="author" maxlength="20"></td>
						</tr>
						<tr>
							<td>出版社</td>
							<td>${book.publisherName }</td>
							<td><select name="publisher">
									<c:forEach items="${publist }" var="pub">
										<option value="${pub.publisherCode }">${pub.publisherCode }.
											${pub.publisherName }</option>
									</c:forEach>
							</select></td>
						</tr>
						<tr>
							<td>出版日</td>
							<td>${book.publicationDay }</td>
							<td><input type="text" id="datepicker" name="publication"
								pattern="^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$">
							</td>
						</tr>

					</tbody>
				</table>
				<input type="submit" value="確認画面へ"> <input type="button"
					value="戻る" onClick="history.back()">
			</form>
		</div>
		<div class="sidebar">
			<script type="text/javascript">
				sidebar();
			</script>
		</div>
	</div>
	<!--/.container-->

	<footer id="footer">
		<script type="text/javascript">
			footer();
		</script>
	</footer>
</body>
</html>